### ISSUE TITLE
💀 some stupid embarissing keyboard layout issue

### ISSUE THREAD

**Issue by chufo4** [majdsassi/Pico-WIFI-Duck#2]
when i type something with it it inputs the english keyboard inputs and not the german layout, how do i change this i tried many times but it didnt work.

**Comment by chufo4** [comment]
fixed

**Comment by chufo4** [comment]
@majdsassi

**Comment by chufo4** [comment]
@majdsassi sorry lol but this is urgent

**Comment by chufo4** [comment]
@majdsassi

**Comment by majdsassi** [comment]
@chufo4 , you have a couple of options to address the keyboard language issue. Firstly, you can manually change the keyboard language, and it should work. Alternatively, you can modify the code itself to accommodate the desired layout. However, please note that the German layout may not be available in CircuitPython version 8. In that case, you'll need to install version 9 and make the necessary changes. Another option is to modify the payload itself. For example, if you have a French layout where the "A" and "Q" keys are switched, you can simply type "Q" instead of "A". Additionally, you can force the target PC to change the language to English using the following payload: (GUI r STRING powershell -command "Set-WinUserLanguageList -Force 'en-US'").

**Comment by chufo4** [comment]
@majdsassi sorry I tried the second option and it didn't work i do need some help with that, also in pico-ducky repo it did work with circuit python 8 , also this is probably retarded but I also tried the reversing thing but it didn't work

**Comment by chufo4** [comment]
the  reversing doesnt work because somehow you cant run payloads that have äöü

**Comment by majdsassi** [comment]
i see , i reccomand forcing the target device language to change to us English

**Comment by chufo4** [comment]
thanks I found out Windows tab does the trick although can I change it directly in the duck py because I couldn't get it do so
